<a href="https://colab.research.google.com/github/JewareSM/Data-Visualization-Tools/blob/main/DSML_Advanced_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Example - we have to find squares of number present in list and numpy_array

''' Lists VS Numpy_array '''

In [ ]:
a = [1,2,3,4,5]

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
a_sq = [ele ** 2 for ele in a]     #List comprehension method

In [ ]:
a_sq

[1, 4, 9, 16, 25]

* To find squares of numbers in list we have 2 methods - 

* 1.The basic apporach is, iterate over the list and square each element.
* 2.We can use list comprehension method.
* This is normal apporach, if you have not learned 'Numpy'.

In [ ]:
#Lets try same think with numpy

import numpy as np

In [ ]:
a_np = np.array(a)        #Passed 'a' in numpy array

In [ ]:
a_np

array([1, 2, 3, 4, 5])

In [ ]:
a_np ** 2

array([ 1,  4,  9, 16, 25])

* What we seen is -

* When we try to find squares of element in list we have write lot of code.


In [ ]:
#Lets check who  is faster lists or numpy_array while performing squares operation 

l = range(100000)

In [ ]:
len(l)

100000

In [ ]:
%timeit [i**2 for i in l]

31.8 ms ± 406 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
l_np = np.arange(1000000)

In [ ]:
len(l_np)

1000000

In [ ]:
%timeit l_np ** 2

1.23 ms ± 106 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


* To perform elementwise operation with lists, lists takes large time to do squaring operation .
* Dose not provides clean syntax. we have to write some lines of code.

* To perform elementwise operation with numpy --
* Numpy provides very clean syntax.
* It takes less time to  time to do elementwise operation. 

* #We can see numpy is faster than python list while calculating squares of numbers in python list and numpy array.
* #If you have to perform elementwise operation,numpy provides
* 1.Clean syntax
* 2.Computational benefits

In [ ]:
#Lets create some numpy array and see some interesting functions to create numpy array

In [ ]:
#1-
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
a = np.array([1,2,3])

In [ ]:
a*2

array([2, 4, 6])

In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#Let's check dimenssion of numpy_array

a.ndim

1

In [ ]:
#Let's check shape of numpy_array

a.shape

(3,)

## Working with 2D arrays -

In [ ]:
import numpy as np

In [ ]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])     #2D array

In [ ]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m1.ndim           #It has two dimenssion row and column

2

In [ ]:
m1.shape

(2, 3)

In [ ]:
#Quiz - What will be the value of b??

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = len(a)

In [ ]:
b

3

In [ ]:
len(np.array([[1, 2, 3], [4, 5, 6]]))


2

If you use len function on 2D lists/array it will tell you no. of elements present in outer list

In [ ]:
#Quiz - What will be output for the following code

a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)                                #Row vector 

[[1 2 3 4 5]]


Here we are converting 1D array to 2D array using ndim

In [ ]:
a.shape

(1, 5)

In [ ]:
m2 = np.arange(1, 13)

In [ ]:
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m2.ndim


1

In [ ]:
m2.shape

(12,)

In [ ]:
m2.reshape(3, 4)     #reshape function

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Here we are reshaping our 1D array to 2D array using reshape function

In [ ]:
m2.reshape(4, 3)       #We have 4 rows and 3 columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m2.reshape(12, 1)      #Column vector

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
a = np.arange(4)
a


array([0, 1, 2, 3])

In [ ]:
a.reshape(2,4)

ValueError: ignored

In [ ]:
c = np.arange(4)
c

array([0, 1, 2, 3])

In [ ]:
np.resize(c, (2, 4))           #resize function

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
#Quiz - What will be the output for the following code

a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


Here we are checking no.of dimenssion for this

In [ ]:
import numpy as np

In [ ]:
a = np.arange(4)
a.resize((2, 4))           #a.resize


In [ ]:
a

array([[0, 1, 2, 3],
       [0, 0, 0, 0]])

In [ ]:
b = np.arange(4)
np.resize(b, (2, 4))       #np.resize

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
c = a

In [ ]:
a.resize((3, 4))

ValueError: ignored

In [ ]:
c.resize((3, 4))

ValueError: ignored

In [ ]:
#Transpose of array - 


a = np.arange(3)

In [ ]:
a

array([0, 1, 2])

In [ ]:
b = a.reshape(1,3)

In [ ]:
b.T

array([[0],
       [1],
       [2]])

In [ ]:
a = np.arange(3).reshape(1,3)

In [ ]:
a

array([[0, 1, 2]])

In [ ]:
a.T

array([[0],
       [1],
       [2]])

In [ ]:
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
a.T

array([0, 1, 2])

In [ ]:
#Flatten function - You have given nD array and you have to flatten that array


a = np.arange(12).reshape(3, 4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(12)            

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(12).shape


(12,)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
a.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
 #Create array of zeros
 np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Create array of ones
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Create array of all 5's with shape (2,3)
np.ones((2, 3)) *5 

array([[5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
#Diagonal matrices
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
#Quiz-

a = np.diag([1,2,3])
b = np.diag(a)

In [ ]:
b

array([1, 2, 3])

In [ ]:
#Identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Indexing and slicing

m1 = np.arange(12)

In [ ]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[0]

0

In [ ]:
m1[12]

IndexError: ignored

In [ ]:
#Quiz- Given 2D array what will be the output of m1[1][2]

m1 = np.arange(1,10).reshape((3,3))
print(m1)
m1[1][2]                             #not use this syntax 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

In [ ]:
m1[1, 2]          #use this syntax

6

In [ ]:
m1 = np.array([100,200,300,400,500,600])

In [ ]:
m1[[2,3,4,1,2,2]]   #You can provide/assign list of indexes to a numpy array

array([300, 400, 500, 200, 300, 300])

In [ ]:
m1 = np.arange(9).reshape((3,3))
m1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
m1[[0, 0, 1], [0, 1, 2]] #important


array([0, 1, 5])

In [ ]:
#Slicing

m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[:5]

array([0, 1, 2, 3, 4])

In [ ]:
m1 = np.array([[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]])

In [ ]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1[0, 1:3]

array([1, 2])

In [ ]:
m1[0,2:]

array([2, 3])

In [ ]:
m1[1,2:]

array([6, 7])

In [ ]:
m1[2,2:]

array([10, 11])

In [ ]:
m1[:,2:]           #Final answer

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
#Quiz - What will be output of m1[0,1:3] ??



In [ ]:
m1 = np.array([[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]])

In [ ]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1[0,1:3]

array([1, 2])

In [ ]:
#Quiz - What will be output of a[4:] = 10 ??


a = np.arange(6)
a


array([0, 1, 2, 3, 4, 5])

In [ ]:
a[4:] = 10          #Here we are combining slicing and assignment operation together


In [ ]:
a

array([ 0,  1,  2,  3, 10, 10])

In [ ]:
#Quiz - What will be the a??

a = np.array([1,2,3,4,5])
b = np.array([8,7,6])


In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
b

array([8, 7, 6])

In [ ]:
a[2:] = b[::-1]

In [ ]:
a

array([1, 2, 6, 7, 8])

In [ ]:
#Fancy indexing - Masking/Mask

m1 = np.arange(12).reshape(3, 4)
m1





array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1 < 6         #mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
m1[m1 < 6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
m1[m1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:

#divisible by 2 or 5                  #Wrong

a[(a %2 == 0) | (a%5 == 0)]

array([5])

In [ ]:
#Quiz - What will be the value of a


a = np.arange(6)
mask = (a%2 == 0)
a[mask] = -1

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
print(a * b)

[1 4 9]


In [ ]:
a = np.array([-1,  1, -1,  3, -1,  5])

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
a.reshape(3, -2)

array([[-1,  1],
       [-1,  3],
       [-1,  5]])

In [ ]:
#Assignment -

In [ ]:
#Q4. Comparing in numpy - 

#a. What is the last element of the output?

import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
#b. What is the output of the code snippet given below?

arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

Explaination:
**For block a**, the array is sorted lexicographically, and the last element accordingly comes out to be ‘Ram’
**For** **block** b, the comparison is made element by element and we can easily see that all the elements in arr1 are lexicographically smaller than arr2 therefore an array of three False is returned.

In [ ]:
#Q6. Numpy on 2D - Given the 2-D array X,
import numpy as np
X = np.arange(12).reshape(3,4)

In [ ]:
X        #So, X is

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#Which of the following is/are true statements.

X.max(axis=1) = ([ 3, 7, 11])

SyntaxError: ignored

In [ ]:
X.sum() = 11

SyntaxError: ignored